env:
  EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
name: Release
on:
  workflow_dispatch: null
jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: install
        run: npm ci || npm install
      - name: build
        run: npm run build
      - name: upload
        run: npm run release
